In [4]:
dev = "AIzaSyC_t1W-rv-JHoyIcPRypT6Asw0vTT5rB98"

In [5]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)

request = youtube.commentThreads().list(
    part="snippet",
    videoId="HrnrqYxYrbk",
    maxResults=100
)

comments = []

# Execute the request.
response = request.execute()

# Get the comments from the response.
for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

while (1 == 1):
  try:
   nextPageToken = response['nextPageToken']
  except KeyError:
   break
  nextPageToken = response['nextPageToken']
  # Create a new request object with the next page token.
  nextRequest = youtube.commentThreads().list(part="snippet", videoId="-GJgqIJsTME", maxResults=100, pageToken=nextPageToken)
  # Execute the next request.
  response = nextRequest.execute()
  # Get the comments from the next response.
  for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

df = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','public'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      795 non-null    object
 1   updated_at  795 non-null    object
 2   like_count  795 non-null    int64
 3   text        795 non-null    object
 4   public      795 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 25.7+ KB

In [8]:
df.isna().sum()

author        0
updated_at    0
like_count    0
text          0
public        0
dtype: int64

In [3]:
df.head(10)

,author,updated_at,like_count,text,public
0,@ActionBronsonMusic,2023-10-23T17:53:02Z,593,PARIS. WITH LOVE.,True
1,@gregoiredoyon4569,2024-05-10T16:07:03Z,0,I need the name of the Bousquet wine at 8:15 min,True
2,@charlesruffing5606,2024-02-13T04:29:12Z,0,My Cats are junkies for this video...They try ...,True
3,@tannerdempster-walsh4962,2024-02-06T20:30:55Z,1,Bro getting drunk all day and eating magical f...,True
4,@donlee1308,2024-02-01T23:40:27Z,0,"hands down, the fuckin best food and wine seri...",True
5,@mehdiflood,2024-02-01T00:47:00Z,0,Clovis!,True
6,@hameedkhumalo4769,2024-01-31T07:15:50Z,0,"These videos just make me smile, THANK YOU.",True
7,@Bennn2013,2024-01-24T02:18:56Z,0,Didn't catch it earlier but man at start of vi...,True
8,@jenkornblum3795,2024-01-17T12:02:18Z,0,so this is great! one thing I am missing is wh...,True
9,@Sssteelo,2024-01-07T03:24:57Z,0,I watched this whole series backwards lol,True

# Sort by Likes and Get Top 10

In [6]:
df.sort_values(by='like_count',ascending=False)[0:10]

,author,updated_at,like_count,text,public
779,@dirtsmegee,2023-10-23T15:05:54Z,1090,Action needs an 8 part series in every country...,True
682,@Nolanbrown480,2023-10-23T16:59:12Z,736,Clovis’ energy is absolutely unmatched. The pe...,True
647,@ActionBronsonMusic,2023-10-23T17:53:02Z,593,PARIS. WITH LOVE.,True
784,@uknownutin3528,2023-10-23T15:01:03Z,531,One of the best food series on YouTube. LONG L...,True
793,@BigTunaBoy420,2023-10-23T12:30:09Z,278,One of the best and most authentic eating shows,True
733,@urbanprojectz,2023-10-23T15:59:02Z,178,This is a game changer for food/cooking/review...,True
757,@elmejortrabajodelmundo,2023-10-23T15:26:47Z,76,"""From Paris with Love"" makes me happy for real...",True
663,@yorkshireguy6671,2023-10-23T17:15:43Z,72,Action and Clovis in Paris always looks like t...,True
792,@cheng8841,2023-10-23T12:57:26Z,69,"""eight part series"" LETS GOOOOOO",True
743,@Raisinsetmelodies,2023-10-23T15:42:38Z,51,Thanks for putting forward the bottles that th...,True